import { Duration, RemovalPolicy, Stack, type StackProps } from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as elasticache from "aws-cdk-lib/aws-elasticache";
import * as kms from "aws-cdk-lib/aws-kms";
import * as rds from "aws-cdk-lib/aws-rds";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import { type Construct } from "constructs";

import { DB_BACKUP_RETENTION_DAYS } from "./constants";

export interface DataStackProps extends StackProps {
  readonly vpc: ec2.IVpc;
  /**
   * Keys are passed by ARN and imported here (immutable IKey). Importing by ARN
   * — rather than receiving the mutable Key object cross-stack — prevents CDK
   * from auto-mutating the key's resource policy from a different stack, which
   * would create a circular stack dependency. The key's resource policy is set
   * once, in SecurityStack.
   */
  readonly databaseKeyArn: string;
}

/**
 * DataStack — Postgres 16 (Multi-AZ, CMK-encrypted) + Redis (STANDARDS §1.1, §8, §17, §18).
 *
 * Postgres (RDS):
 *  - Multi-AZ for HA; isolated subnets only; not publicly accessible.
 *  - StorageEncrypted with a customer-managed KMS key (INV-AUDIT-4).
 *  - Deletion protection ON; automated backups (PITR window) retained.
 *  - Performance Insights enabled.
 *  - Master credentials GENERATED into Secrets Manager — never inline (§17).
 *
 * Redis (ElastiCache):
 *  - Encryption at rest (CMK) AND in transit; private (isolated) subnets only;
 *    no public access (the cache/queue backbone for BullMQ — STANDARDS §15).
 */
export class DataStack extends Stack {
  public readonly database: rds.DatabaseInstance;
  public readonly databaseSecret: secretsmanager.ISecret;
  public readonly redis: elasticache.CfnReplicationGroup;
  public readonly redisKey: kms.Key;

  public constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    const { vpc } = props;
    const databaseKey = kms.Key.fromKeyArn(
      this,
      "ImportedDatabaseKey",
      props.databaseKeyArn,
    );

    // Redis CMK is created in this stack (its only consumer) — rotated, like all
    // ProBooks CMKs — to avoid a cross-stack key-policy dependency cycle.
    this.redisKey = new kms.Key(this, "RedisKey", {
      description: "ProBooks ElastiCache Redis encryption (CMK, rotated)",
      enableKeyRotation: true,
      alias: "alias/probooks/redis",
    });
    const redisKey = this.redisKey;

    // Master credentials generated into Secrets Manager (STANDARDS §17). No
    // plaintext password is ever placed in the template; the username is fixed
    // and the password is generated by the secret.
    const credentials = rds.Credentials.fromGeneratedSecret("probooks_admin", {
      secretName: "probooks/rds/credentials",
      encryptionKey: databaseKey,
    });

    this.database = new rds.DatabaseInstance(this, "Postgres", {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16,
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.M6G,
        ec2.InstanceSize.LARGE,
      ),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      multiAz: true,
      publiclyAccessible: false,
      storageEncrypted: true,
      storageEncryptionKey: databaseKey,
      credentials,
      deletionProtection: true,
      backupRetention: Duration.days(DB_BACKUP_RETENTION_DAYS),
      enablePerformanceInsights: true,
      performanceInsightEncryptionKey: databaseKey,
      // Retain the database (and its data) even if the stack is destroyed —
      // financial data is never destructively removed (STANDARDS §15 / §29).
      removalPolicy: RemovalPolicy.RETAIN,
    });

    this.databaseSecret = this.database.secret as secretsmanager.ISecret;

    // ----- Redis (ElastiCache replication group) -----------------------------

    const redisSubnetGroup = new elasticache.CfnSubnetGroup(
      this,
      "RedisSubnetGroup",
      {
        description: "ProBooks Redis — isolated subnets only",
        subnetIds: vpc.selectSubnets({
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
        }).subnetIds,
      },
    );

    const redisSecurityGroup = new ec2.SecurityGroup(
      this,
      "RedisSecurityGroup",
      {
        vpc,
        description: "ProBooks Redis — no public ingress",
        allowAllOutbound: false,
      },
    );

    this.redis = new elasticache.CfnReplicationGroup(this, "Redis", {
      replicationGroupDescription: "ProBooks cache + BullMQ backbone",
      engine: "redis",
      cacheNodeType: "cache.m6g.large",
      numNodeGroups: 1,
      replicasPerNodeGroup: 1,
      automaticFailoverEnabled: true,
      multiAzEnabled: true,
      atRestEncryptionEnabled: true,
      transitEncryptionEnabled: true,
      kmsKeyId: redisKey.keyId,
      cacheSubnetGroupName: redisSubnetGroup.ref,
      securityGroupIds: [redisSecurityGroup.securityGroupId],
    });
  }
}
